default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: docker_study/dev

test:
  <<: *default
  database: docker_study/test

production:
  <<: *default
  database: docker_study/prod
